// protos/fabricx.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/fabricx.proto

package grpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkName   string                 `protobuf:"bytes,1,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	NumOrgs       int32                  `protobuf:"varint,2,opt,name=num_orgs,json=numOrgs,proto3" json:"num_orgs,omitempty"`
	ChannelName   string                 `protobuf:"bytes,3,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitNetworkRequest) Reset() {
	*x = InitNetworkRequest{}
	mi := &file_protos_fabricx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitNetworkRequest) ProtoMessage() {}

func (x *InitNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitNetworkRequest.ProtoReflect.Descriptor instead.
func (*InitNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{0}
}

func (x *InitNetworkRequest) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *InitNetworkRequest) GetNumOrgs() int32 {
	if x != nil {
		return x.NumOrgs
	}
	return 0
}

func (x *InitNetworkRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *InitNetworkRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NetworkId     string                 `protobuf:"bytes,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Endpoints     []string               `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitNetworkResponse) Reset() {
	*x = InitNetworkResponse{}
	mi := &file_protos_fabricx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitNetworkResponse) ProtoMessage() {}

func (x *InitNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitNetworkResponse.ProtoReflect.Descriptor instead.
func (*InitNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{1}
}

func (x *InitNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitNetworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitNetworkResponse) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *InitNetworkResponse) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type DeployChaincodeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NetworkId             string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChaincodeName         string                 `protobuf:"bytes,2,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	ChaincodePath         string                 `protobuf:"bytes,3,opt,name=chaincode_path,json=chaincodePath,proto3" json:"chaincode_path,omitempty"`
	Version               string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Language              string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	EndorsementPolicyOrgs []string               `protobuf:"bytes,6,rep,name=endorsement_policy_orgs,json=endorsementPolicyOrgs,proto3" json:"endorsement_policy_orgs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeployChaincodeRequest) Reset() {
	*x = DeployChaincodeRequest{}
	mi := &file_protos_fabricx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployChaincodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployChaincodeRequest) ProtoMessage() {}

func (x *DeployChaincodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployChaincodeRequest.ProtoReflect.Descriptor instead.
func (*DeployChaincodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{2}
}

func (x *DeployChaincodeRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *DeployChaincodeRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *DeployChaincodeRequest) GetChaincodePath() string {
	if x != nil {
		return x.ChaincodePath
	}
	return ""
}

func (x *DeployChaincodeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeployChaincodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DeployChaincodeRequest) GetEndorsementPolicyOrgs() []string {
	if x != nil {
		return x.EndorsementPolicyOrgs
	}
	return nil
}

type DeployChaincodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ChaincodeId   string                 `protobuf:"bytes,3,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployChaincodeResponse) Reset() {
	*x = DeployChaincodeResponse{}
	mi := &file_protos_fabricx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployChaincodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployChaincodeResponse) ProtoMessage() {}

func (x *DeployChaincodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployChaincodeResponse.ProtoReflect.Descriptor instead.
func (*DeployChaincodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{3}
}

func (x *DeployChaincodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployChaincodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployChaincodeResponse) GetChaincodeId() string {
	if x != nil {
		return x.ChaincodeId
	}
	return ""
}

type InvokeTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChaincodeName string                 `protobuf:"bytes,2,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	FunctionName  string                 `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Transient     bool                   `protobuf:"varint,5,opt,name=transient,proto3" json:"transient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTransactionRequest) Reset() {
	*x = InvokeTransactionRequest{}
	mi := &file_protos_fabricx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTransactionRequest) ProtoMessage() {}

func (x *InvokeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTransactionRequest.ProtoReflect.Descriptor instead.
func (*InvokeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeTransactionRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *InvokeTransactionRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *InvokeTransactionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *InvokeTransactionRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *InvokeTransactionRequest) GetTransient() bool {
	if x != nil {
		return x.Transient
	}
	return false
}

type InvokeTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTransactionResponse) Reset() {
	*x = InvokeTransactionResponse{}
	mi := &file_protos_fabricx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTransactionResponse) ProtoMessage() {}

func (x *InvokeTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTransactionResponse.ProtoReflect.Descriptor instead.
func (*InvokeTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{5}
}

func (x *InvokeTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvokeTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvokeTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *InvokeTransactionResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QueryLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChaincodeName string                 `protobuf:"bytes,2,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	FunctionName  string                 `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLedgerRequest) Reset() {
	*x = QueryLedgerRequest{}
	mi := &file_protos_fabricx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLedgerRequest) ProtoMessage() {}

func (x *QueryLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLedgerRequest.ProtoReflect.Descriptor instead.
func (*QueryLedgerRequest) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{6}
}

func (x *QueryLedgerRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *QueryLedgerRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *QueryLedgerRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *QueryLedgerRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type QueryLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLedgerResponse) Reset() {
	*x = QueryLedgerResponse{}
	mi := &file_protos_fabricx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLedgerResponse) ProtoMessage() {}

func (x *QueryLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLedgerResponse.ProtoReflect.Descriptor instead.
func (*QueryLedgerResponse) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{7}
}

func (x *QueryLedgerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryLedgerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryLedgerResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StopNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Cleanup       bool                   `protobuf:"varint,2,opt,name=cleanup,proto3" json:"cleanup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopNetworkRequest) Reset() {
	*x = StopNetworkRequest{}
	mi := &file_protos_fabricx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNetworkRequest) ProtoMessage() {}

func (x *StopNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNetworkRequest.ProtoReflect.Descriptor instead.
func (*StopNetworkRequest) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{8}
}

func (x *StopNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *StopNetworkRequest) GetCleanup() bool {
	if x != nil {
		return x.Cleanup
	}
	return false
}

type StopNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopNetworkResponse) Reset() {
	*x = StopNetworkResponse{}
	mi := &file_protos_fabricx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNetworkResponse) ProtoMessage() {}

func (x *StopNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNetworkResponse.ProtoReflect.Descriptor instead.
func (*StopNetworkResponse) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{9}
}

func (x *StopNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopNetworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NetworkStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatusRequest) Reset() {
	*x = NetworkStatusRequest{}
	mi := &file_protos_fabricx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatusRequest) ProtoMessage() {}

func (x *NetworkStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatusRequest.ProtoReflect.Descriptor instead.
func (*NetworkStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkStatusRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

type NetworkStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Peers         []*PeerStatus          `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	Orderers      []*OrdererStatus       `protobuf:"bytes,4,rep,name=orderers,proto3" json:"orderers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatusResponse) Reset() {
	*x = NetworkStatusResponse{}
	mi := &file_protos_fabricx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatusResponse) ProtoMessage() {}

func (x *NetworkStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatusResponse.ProtoReflect.Descriptor instead.
func (*NetworkStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *NetworkStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NetworkStatusResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NetworkStatusResponse) GetOrderers() []*OrdererStatus {
	if x != nil {
		return x.Orderers
	}
	return nil
}

type PeerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_protos_fabricx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{12}
}

func (x *PeerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerStatus) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *PeerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PeerStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type OrdererStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdererStatus) Reset() {
	*x = OrdererStatus{}
	mi := &file_protos_fabricx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdererStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdererStatus) ProtoMessage() {}

func (x *OrdererStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdererStatus.ProtoReflect.Descriptor instead.
func (*OrdererStatus) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{13}
}

func (x *OrdererStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrdererStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrdererStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_protos_fabricx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{14}
}

func (x *StreamLogsRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *StreamLogsRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_protos_fabricx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fabricx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_protos_fabricx_proto_rawDescGZIP(), []int{15}
}

func (x *LogMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogMessage) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_fabricx_proto protoreflect.FileDescriptor

const file_protos_fabricx_proto_rawDesc = "" +
	"\n" +
	"\x14protos/fabricx.proto\x12\afabricx\"\xf1\x01\n" +
	"\x12InitNetworkRequest\x12!\n" +
	"\fnetwork_name\x18\x01 \x01(\tR\vnetworkName\x12\x19\n" +
	"\bnum_orgs\x18\x02 \x01(\x05R\anumOrgs\x12!\n" +
	"\fchannel_name\x18\x03 \x01(\tR\vchannelName\x12?\n" +
	"\x06config\x18\x04 \x03(\v2'.fabricx.InitNetworkRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x13InitNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"network_id\x18\x03 \x01(\tR\tnetworkId\x12\x1c\n" +
	"\tendpoints\x18\x04 \x03(\tR\tendpoints\"\xf3\x01\n" +
	"\x16DeployChaincodeRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12%\n" +
	"\x0echaincode_name\x18\x02 \x01(\tR\rchaincodeName\x12%\n" +
	"\x0echaincode_path\x18\x03 \x01(\tR\rchaincodePath\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x126\n" +
	"\x17endorsement_policy_orgs\x18\x06 \x03(\tR\x15endorsementPolicyOrgs\"p\n" +
	"\x17DeployChaincodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fchaincode_id\x18\x03 \x01(\tR\vchaincodeId\"\xb7\x01\n" +
	"\x18InvokeTransactionRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12%\n" +
	"\x0echaincode_name\x18\x02 \x01(\tR\rchaincodeName\x12#\n" +
	"\rfunction_name\x18\x03 \x01(\tR\ffunctionName\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x1c\n" +
	"\ttransient\x18\x05 \x01(\bR\ttransient\"\x90\x01\n" +
	"\x19InvokeTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x93\x01\n" +
	"\x12QueryLedgerRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12%\n" +
	"\x0echaincode_name\x18\x02 \x01(\tR\rchaincodeName\x12#\n" +
	"\rfunction_name\x18\x03 \x01(\tR\ffunctionName\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\"c\n" +
	"\x13QueryLedgerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"M\n" +
	"\x12StopNetworkRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x18\n" +
	"\acleanup\x18\x02 \x01(\bR\acleanup\"I\n" +
	"\x13StopNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x14NetworkStatusRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\"\xa8\x01\n" +
	"\x15NetworkStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x05peers\x18\x03 \x03(\v2\x13.fabricx.PeerStatusR\x05peers\x122\n" +
	"\borderers\x18\x04 \x03(\v2\x16.fabricx.OrdererStatusR\borderers\"f\n" +
	"\n" +
	"PeerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\"W\n" +
	"\rOrdererStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"Y\n" +
	"\x11StreamLogsRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\"b\n" +
	"\n" +
	"LogMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xb4\x04\n" +
	"\x0eFabricXService\x12H\n" +
	"\vInitNetwork\x12\x1b.fabricx.InitNetworkRequest\x1a\x1c.fabricx.InitNetworkResponse\x12T\n" +
	"\x0fDeployChaincode\x12\x1f.fabricx.DeployChaincodeRequest\x1a .fabricx.DeployChaincodeResponse\x12Z\n" +
	"\x11InvokeTransaction\x12!.fabricx.InvokeTransactionRequest\x1a\".fabricx.InvokeTransactionResponse\x12H\n" +
	"\vQueryLedger\x12\x1b.fabricx.QueryLedgerRequest\x1a\x1c.fabricx.QueryLedgerResponse\x12H\n" +
	"\vStopNetwork\x12\x1b.fabricx.StopNetworkRequest\x1a\x1c.fabricx.StopNetworkResponse\x12Q\n" +
	"\x10GetNetworkStatus\x12\x1d.fabricx.NetworkStatusRequest\x1a\x1e.fabricx.NetworkStatusResponse\x12?\n" +
	"\n" +
	"StreamLogs\x12\x1a.fabricx.StreamLogsRequest\x1a\x13.fabricx.LogMessage0\x01B4Z2github.com/temmyjay001/fabricx-core/pkg/grpcserverb\x06proto3"

var (
	file_protos_fabricx_proto_rawDescOnce sync.Once
	file_protos_fabricx_proto_rawDescData []byte
)

func file_protos_fabricx_proto_rawDescGZIP() []byte {
	file_protos_fabricx_proto_rawDescOnce.Do(func() {
		file_protos_fabricx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_fabricx_proto_rawDesc), len(file_protos_fabricx_proto_rawDesc)))
	})
	return file_protos_fabricx_proto_rawDescData
}

var file_protos_fabricx_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protos_fabricx_proto_goTypes = []any{
	(*InitNetworkRequest)(nil),        // 0: fabricx.InitNetworkRequest
	(*InitNetworkResponse)(nil),       // 1: fabricx.InitNetworkResponse
	(*DeployChaincodeRequest)(nil),    // 2: fabricx.DeployChaincodeRequest
	(*DeployChaincodeResponse)(nil),   // 3: fabricx.DeployChaincodeResponse
	(*InvokeTransactionRequest)(nil),  // 4: fabricx.InvokeTransactionRequest
	(*InvokeTransactionResponse)(nil), // 5: fabricx.InvokeTransactionResponse
	(*QueryLedgerRequest)(nil),        // 6: fabricx.QueryLedgerRequest
	(*QueryLedgerResponse)(nil),       // 7: fabricx.QueryLedgerResponse
	(*StopNetworkRequest)(nil),        // 8: fabricx.StopNetworkRequest
	(*StopNetworkResponse)(nil),       // 9: fabricx.StopNetworkResponse
	(*NetworkStatusRequest)(nil),      // 10: fabricx.NetworkStatusRequest
	(*NetworkStatusResponse)(nil),     // 11: fabricx.NetworkStatusResponse
	(*PeerStatus)(nil),                // 12: fabricx.PeerStatus
	(*OrdererStatus)(nil),             // 13: fabricx.OrdererStatus
	(*StreamLogsRequest)(nil),         // 14: fabricx.StreamLogsRequest
	(*LogMessage)(nil),                // 15: fabricx.LogMessage
	nil,                               // 16: fabricx.InitNetworkRequest.ConfigEntry
}
var file_protos_fabricx_proto_depIdxs = []int32{
	16, // 0: fabricx.InitNetworkRequest.config:type_name -> fabricx.InitNetworkRequest.ConfigEntry
	12, // 1: fabricx.NetworkStatusResponse.peers:type_name -> fabricx.PeerStatus
	13, // 2: fabricx.NetworkStatusResponse.orderers:type_name -> fabricx.OrdererStatus
	0,  // 3: fabricx.FabricXService.InitNetwork:input_type -> fabricx.InitNetworkRequest
	2,  // 4: fabricx.FabricXService.DeployChaincode:input_type -> fabricx.DeployChaincodeRequest
	4,  // 5: fabricx.FabricXService.InvokeTransaction:input_type -> fabricx.InvokeTransactionRequest
	6,  // 6: fabricx.FabricXService.QueryLedger:input_type -> fabricx.QueryLedgerRequest
	8,  // 7: fabricx.FabricXService.StopNetwork:input_type -> fabricx.StopNetworkRequest
	10, // 8: fabricx.FabricXService.GetNetworkStatus:input_type -> fabricx.NetworkStatusRequest
	14, // 9: fabricx.FabricXService.StreamLogs:input_type -> fabricx.StreamLogsRequest
	1,  // 10: fabricx.FabricXService.InitNetwork:output_type -> fabricx.InitNetworkResponse
	3,  // 11: fabricx.FabricXService.DeployChaincode:output_type -> fabricx.DeployChaincodeResponse
	5,  // 12: fabricx.FabricXService.InvokeTransaction:output_type -> fabricx.InvokeTransactionResponse
	7,  // 13: fabricx.FabricXService.QueryLedger:output_type -> fabricx.QueryLedgerResponse
	9,  // 14: fabricx.FabricXService.StopNetwork:output_type -> fabricx.StopNetworkResponse
	11, // 15: fabricx.FabricXService.GetNetworkStatus:output_type -> fabricx.NetworkStatusResponse
	15, // 16: fabricx.FabricXService.StreamLogs:output_type -> fabricx.LogMessage
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_fabricx_proto_init() }
func file_protos_fabricx_proto_init() {
	if File_protos_fabricx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_fabricx_proto_rawDesc), len(file_protos_fabricx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_fabricx_proto_goTypes,
		DependencyIndexes: file_protos_fabricx_proto_depIdxs,
		MessageInfos:      file_protos_fabricx_proto_msgTypes,
	}.Build()
	File_protos_fabricx_proto = out.File
	file_protos_fabricx_proto_goTypes = nil
	file_protos_fabricx_proto_depIdxs = nil
}
