// protos/fabricx.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: protos/fabricx.proto

package grpcserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FabricXService_InitNetwork_FullMethodName       = "/fabricx.FabricXService/InitNetwork"
	FabricXService_DeployChaincode_FullMethodName   = "/fabricx.FabricXService/DeployChaincode"
	FabricXService_InvokeTransaction_FullMethodName = "/fabricx.FabricXService/InvokeTransaction"
	FabricXService_QueryLedger_FullMethodName       = "/fabricx.FabricXService/QueryLedger"
	FabricXService_StopNetwork_FullMethodName       = "/fabricx.FabricXService/StopNetwork"
	FabricXService_GetNetworkStatus_FullMethodName  = "/fabricx.FabricXService/GetNetworkStatus"
	FabricXService_StreamLogs_FullMethodName        = "/fabricx.FabricXService/StreamLogs"
)

// FabricXServiceClient is the client API for FabricXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FabricXServiceClient interface {
	InitNetwork(ctx context.Context, in *InitNetworkRequest, opts ...grpc.CallOption) (*InitNetworkResponse, error)
	DeployChaincode(ctx context.Context, in *DeployChaincodeRequest, opts ...grpc.CallOption) (*DeployChaincodeResponse, error)
	InvokeTransaction(ctx context.Context, in *InvokeTransactionRequest, opts ...grpc.CallOption) (*InvokeTransactionResponse, error)
	QueryLedger(ctx context.Context, in *QueryLedgerRequest, opts ...grpc.CallOption) (*QueryLedgerResponse, error)
	StopNetwork(ctx context.Context, in *StopNetworkRequest, opts ...grpc.CallOption) (*StopNetworkResponse, error)
	GetNetworkStatus(ctx context.Context, in *NetworkStatusRequest, opts ...grpc.CallOption) (*NetworkStatusResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error)
}

type fabricXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricXServiceClient(cc grpc.ClientConnInterface) FabricXServiceClient {
	return &fabricXServiceClient{cc}
}

func (c *fabricXServiceClient) InitNetwork(ctx context.Context, in *InitNetworkRequest, opts ...grpc.CallOption) (*InitNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitNetworkResponse)
	err := c.cc.Invoke(ctx, FabricXService_InitNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricXServiceClient) DeployChaincode(ctx context.Context, in *DeployChaincodeRequest, opts ...grpc.CallOption) (*DeployChaincodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployChaincodeResponse)
	err := c.cc.Invoke(ctx, FabricXService_DeployChaincode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricXServiceClient) InvokeTransaction(ctx context.Context, in *InvokeTransactionRequest, opts ...grpc.CallOption) (*InvokeTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeTransactionResponse)
	err := c.cc.Invoke(ctx, FabricXService_InvokeTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricXServiceClient) QueryLedger(ctx context.Context, in *QueryLedgerRequest, opts ...grpc.CallOption) (*QueryLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLedgerResponse)
	err := c.cc.Invoke(ctx, FabricXService_QueryLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricXServiceClient) StopNetwork(ctx context.Context, in *StopNetworkRequest, opts ...grpc.CallOption) (*StopNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopNetworkResponse)
	err := c.cc.Invoke(ctx, FabricXService_StopNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricXServiceClient) GetNetworkStatus(ctx context.Context, in *NetworkStatusRequest, opts ...grpc.CallOption) (*NetworkStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkStatusResponse)
	err := c.cc.Invoke(ctx, FabricXService_GetNetworkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricXServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FabricXService_ServiceDesc.Streams[0], FabricXService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FabricXService_StreamLogsClient = grpc.ServerStreamingClient[LogMessage]

// FabricXServiceServer is the server API for FabricXService service.
// All implementations must embed UnimplementedFabricXServiceServer
// for forward compatibility.
type FabricXServiceServer interface {
	InitNetwork(context.Context, *InitNetworkRequest) (*InitNetworkResponse, error)
	DeployChaincode(context.Context, *DeployChaincodeRequest) (*DeployChaincodeResponse, error)
	InvokeTransaction(context.Context, *InvokeTransactionRequest) (*InvokeTransactionResponse, error)
	QueryLedger(context.Context, *QueryLedgerRequest) (*QueryLedgerResponse, error)
	StopNetwork(context.Context, *StopNetworkRequest) (*StopNetworkResponse, error)
	GetNetworkStatus(context.Context, *NetworkStatusRequest) (*NetworkStatusResponse, error)
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogMessage]) error
	mustEmbedUnimplementedFabricXServiceServer()
}

// UnimplementedFabricXServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFabricXServiceServer struct{}

func (UnimplementedFabricXServiceServer) InitNetwork(context.Context, *InitNetworkRequest) (*InitNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitNetwork not implemented")
}
func (UnimplementedFabricXServiceServer) DeployChaincode(context.Context, *DeployChaincodeRequest) (*DeployChaincodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployChaincode not implemented")
}
func (UnimplementedFabricXServiceServer) InvokeTransaction(context.Context, *InvokeTransactionRequest) (*InvokeTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeTransaction not implemented")
}
func (UnimplementedFabricXServiceServer) QueryLedger(context.Context, *QueryLedgerRequest) (*QueryLedgerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLedger not implemented")
}
func (UnimplementedFabricXServiceServer) StopNetwork(context.Context, *StopNetworkRequest) (*StopNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopNetwork not implemented")
}
func (UnimplementedFabricXServiceServer) GetNetworkStatus(context.Context, *NetworkStatusRequest) (*NetworkStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkStatus not implemented")
}
func (UnimplementedFabricXServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedFabricXServiceServer) mustEmbedUnimplementedFabricXServiceServer() {}
func (UnimplementedFabricXServiceServer) testEmbeddedByValue()                        {}

// UnsafeFabricXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FabricXServiceServer will
// result in compilation errors.
type UnsafeFabricXServiceServer interface {
	mustEmbedUnimplementedFabricXServiceServer()
}

func RegisterFabricXServiceServer(s grpc.ServiceRegistrar, srv FabricXServiceServer) {
	// If the following call pancis, it indicates UnimplementedFabricXServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FabricXService_ServiceDesc, srv)
}

func _FabricXService_InitNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricXServiceServer).InitNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricXService_InitNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricXServiceServer).InitNetwork(ctx, req.(*InitNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricXService_DeployChaincode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployChaincodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricXServiceServer).DeployChaincode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricXService_DeployChaincode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricXServiceServer).DeployChaincode(ctx, req.(*DeployChaincodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricXService_InvokeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricXServiceServer).InvokeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricXService_InvokeTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricXServiceServer).InvokeTransaction(ctx, req.(*InvokeTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricXService_QueryLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricXServiceServer).QueryLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricXService_QueryLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricXServiceServer).QueryLedger(ctx, req.(*QueryLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricXService_StopNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricXServiceServer).StopNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricXService_StopNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricXServiceServer).StopNetwork(ctx, req.(*StopNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricXService_GetNetworkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricXServiceServer).GetNetworkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricXService_GetNetworkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricXServiceServer).GetNetworkStatus(ctx, req.(*NetworkStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricXService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FabricXServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FabricXService_StreamLogsServer = grpc.ServerStreamingServer[LogMessage]

// FabricXService_ServiceDesc is the grpc.ServiceDesc for FabricXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FabricXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fabricx.FabricXService",
	HandlerType: (*FabricXServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitNetwork",
			Handler:    _FabricXService_InitNetwork_Handler,
		},
		{
			MethodName: "DeployChaincode",
			Handler:    _FabricXService_DeployChaincode_Handler,
		},
		{
			MethodName: "InvokeTransaction",
			Handler:    _FabricXService_InvokeTransaction_Handler,
		},
		{
			MethodName: "QueryLedger",
			Handler:    _FabricXService_QueryLedger_Handler,
		},
		{
			MethodName: "StopNetwork",
			Handler:    _FabricXService_StopNetwork_Handler,
		},
		{
			MethodName: "GetNetworkStatus",
			Handler:    _FabricXService_GetNetworkStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _FabricXService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/fabricx.proto",
}
